// GENERATED by scenario_creator. Do not edit by hand.
// Kaynak: scenario_creator/dribble/*.json  (schema 1)
// Uretim: 2026-09-17T19:17:58+03:00
//
// Koridor koordinatlari: `distance` bitise kadarki mesafe (birim =
// koridor genisligi), `x` 0..1 yanal yer (0.5 orta).

typedef DribbleConeSpec = ({double distance, double x});

typedef DribbleCourseSpec = ({
  String id,
  String name,
  String brief,
  double courseLength,
  double timeLimit,
  List<DribbleConeSpec> cones,
});

const kDribbleCourseSpecs = <DribbleCourseSpec>[
  (
    id: 'varsayilan-kurs',
    name: 'Varsayılan kurs',
    brief: 'Önce tek koni, sonra yana kaçık çiftler, sonunda dar bir geçit.',
    courseLength: 10.0000,
    timeLimit: 22.0000,
    cones: [(distance: 1.6000, x: 0.5000), (distance: 2.8000, x: 0.3200), (distance: 3.6000, x: 0.6800), (distance: 4.8000, x: 0.3800), (distance: 5.2000, x: 0.7200), (distance: 6.4000, x: 0.5000), (distance: 7.3000, x: 0.2800), (distance: 7.9000, x: 0.6200), (distance: 8.8000, x: 0.4400), (distance: 9.3000, x: 0.7000)],
  ),
];
