// GENERATED by formation_creator. Do not edit by hand.
// Kaynak: ../formation_creator/formations/*.json  (schema 1) — bu repo'nun
// disinda. Formasyonlar degisince dosya formation_creator'in out/ ciktisindan
// yeniden kopyalanir; asagidaki uretim damgasi hangi surumun gomulu oldugunu
// soyler. career_engine yalnizca formasyon *id*'sini yollar (M1 formation_id),
// slot koordinatlari burada durur.
// Uretim: 2026-09-10T21:50:40+03:00
//
// Koordinat sozlesmesi:
//   x: 0 = sol tac cizgisi,    1 = sag tac cizgisi (hucum yonune bakarken)
//   y: 0 = kendi kale cizgisi, 1 = rakip kale cizgisi
//   Saha: 105 m (y ekseni) x 68 m (x ekseni)

class FormationSlot {
  const FormationSlot({
    required this.x,
    required this.y,
    required this.label,
    this.roleId,
    this.group,
  });

  final double x;
  final double y;
  final String label;
  final String? roleId;
  final String? group;
}

class Formation {
  const Formation({
    required this.id,
    required this.name,
    required this.shape,
    required this.slots,
  });

  final String id;
  final String name;
  final String shape;
  final List<FormationSlot> slots;
}


const kFormations = <Formation>[
  Formation(
    id: '3-4-3-cift10',
    name: '3-4-3(cift10)',
    shape: '3-4-3',
    slots: [
      FormationSlot(x: 0.0747, y: 0.4999, label: 'Sol Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.2327, y: 0.1752, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.7505, y: 0.1824, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.9309, y: 0.5023, label: 'Sağ Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.4945, y: 0.1808, label: 'Libero', roleId: 'libero', group: 'DC'),
      FormationSlot(x: 0.3639, y: 0.5002, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.6491, y: 0.5013, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3639, y: 0.7166, label: 'Sol Kanat', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.6491, y: 0.7141, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.5057, y: 0.8445, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '3-5-2-atak',
    name: '3-5-2(atak)',
    shape: '3-5-2',
    slots: [
      FormationSlot(x: 0.0747, y: 0.4999, label: 'Sol Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.2327, y: 0.1752, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.7505, y: 0.1824, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.9309, y: 0.5023, label: 'Sağ Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.4945, y: 0.1808, label: 'Libero', roleId: 'libero', group: 'DC'),
      FormationSlot(x: 0.3023, y: 0.5014, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7088, y: 0.5001, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3023, y: 0.8447, label: 'Sol Kanat', roleId: 'firsatci_forvet', group: 'ST'),
      FormationSlot(x: 0.4945, y: 0.5970, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.7088, y: 0.8447, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '3-5-2-savunma',
    name: '3-5-2(savunma)',
    shape: '3-5-2',
    slots: [
      FormationSlot(x: 0.0747, y: 0.4999, label: 'Sol Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.2327, y: 0.1752, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.7505, y: 0.1824, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.9309, y: 0.5023, label: 'Sağ Bek', roleId: 'kanat_bek', group: 'DL/DR'),
      FormationSlot(x: 0.4945, y: 0.1808, label: 'Libero', roleId: 'libero', group: 'DC'),
      FormationSlot(x: 0.3023, y: 0.5014, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7088, y: 0.5001, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3023, y: 0.8447, label: 'Sol Kanat', roleId: 'firsatci_forvet', group: 'ST'),
      FormationSlot(x: 0.5001, y: 0.4256, label: 'Regista', roleId: 'regista', group: 'DM'),
      FormationSlot(x: 0.7088, y: 0.8447, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '4-2-3-1',
    name: '4-2-3-1',
    shape: '4-2-3-1',
    slots: [
      FormationSlot(x: 0.1400, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6200, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1800, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.4963, y: 0.6413, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.2800, y: 0.4400, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7200, y: 0.4400, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.1500, y: 0.6413, label: 'Sol Kanat', roleId: 'kanat', group: 'Kanat'),
      FormationSlot(x: 0.5000, y: 0.8000, label: 'Forvet', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.8668, y: 0.6413, label: 'Sağ Kanat', roleId: 'kanat', group: 'Kanat'),
    ],
  ),
  Formation(
    id: '4-3-3-duz',
    name: '4-3-3(duz)',
    shape: '4-3-3',
    slots: [
      FormationSlot(x: 0.1400, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6200, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1800, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.5000, y: 0.4986, label: 'Oyun Kurucu', roleId: 'oyun_kurucu', group: 'MC'),
      FormationSlot(x: 0.2204, y: 0.4986, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7498, y: 0.4986, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.1500, y: 0.7600, label: 'Sol Kanat', roleId: 'kanat', group: 'Kanat'),
      FormationSlot(x: 0.5000, y: 0.8000, label: 'Forvet', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.8500, y: 0.7600, label: 'Sağ Kanat', roleId: 'kanat', group: 'Kanat'),
    ],
  ),
  Formation(
    id: '4-3-3-yuksek-pres',
    name: '4-3-3 Yüksek Pres',
    shape: '4-3-3',
    slots: [
      FormationSlot(x: 0.1400, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6200, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1800, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.5000, y: 0.3800, label: 'Defansif Orta Saha', roleId: 'defansif_orta_saha', group: 'DM'),
      FormationSlot(x: 0.2800, y: 0.4600, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7200, y: 0.4600, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.1500, y: 0.7600, label: 'Sol Kanat', roleId: 'kanat', group: 'Kanat'),
      FormationSlot(x: 0.5000, y: 0.8000, label: 'Forvet', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.8500, y: 0.7600, label: 'Sağ Kanat', roleId: 'kanat', group: 'Kanat'),
    ],
  ),
  Formation(
    id: '4-4-2-diamond-kanat',
    name: '4-4-2 diamond(kanat)',
    shape: '4-4-2',
    slots: [
      FormationSlot(x: 0.1381, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6181, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1800, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.4982, y: 0.3800, label: 'Defansif Orta Saha', roleId: 'defansif_orta_saha', group: 'DM'),
      FormationSlot(x: 0.2800, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7200, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.1381, y: 0.8409, label: 'Sol Kanat', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.4982, y: 0.6164, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.8600, y: 0.8445, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '4-4-2-diamond-st',
    name: '4-4-2 diamond(st)',
    shape: '4-4-2',
    slots: [
      FormationSlot(x: 0.1400, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6181, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1800, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.4982, y: 0.3800, label: 'Defansif Orta Saha', roleId: 'defansif_orta_saha', group: 'DM'),
      FormationSlot(x: 0.2800, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7200, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3800, y: 0.8445, label: 'Sol Kanat', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.4982, y: 0.6164, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.6181, y: 0.8445, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '4-4-2-duz',
    name: '4-4-2 duz',
    shape: '4-4-2',
    slots: [
      FormationSlot(x: 0.1400, y: 0.1800, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.3800, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.6181, y: 0.1800, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.8600, y: 0.1788, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.6181, y: 0.5050, label: 'Mezzala', roleId: 'mezzala', group: 'MC'),
      FormationSlot(x: 0.1400, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.8600, y: 0.5050, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3800, y: 0.8445, label: 'Sol Kanat', roleId: 'forvet', group: 'ST'),
      FormationSlot(x: 0.3800, y: 0.5050, label: 'Oyun Kurucu', roleId: 'oyun_kurucu', group: 'MC'),
      FormationSlot(x: 0.6181, y: 0.8445, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '5-3-2-atak',
    name: '5-3-2(atak)',
    shape: '5-3-2',
    slots: [
      FormationSlot(x: 0.0766, y: 0.2099, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.2327, y: 0.1752, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.7505, y: 0.1824, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.9328, y: 0.2099, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.4945, y: 0.1808, label: 'Libero', roleId: 'libero', group: 'DC'),
      FormationSlot(x: 0.3023, y: 0.5014, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7088, y: 0.5001, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3023, y: 0.8447, label: 'Sol Kanat', roleId: 'firsatci_forvet', group: 'ST'),
      FormationSlot(x: 0.4945, y: 0.5970, label: 'Ofansif Orta Saha', roleId: 'ofansif_orta_saha', group: 'AMC'),
      FormationSlot(x: 0.7088, y: 0.8447, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
  Formation(
    id: '5-3-2-savunma',
    name: '5-3-2(savunma)',
    shape: '5-3-2',
    slots: [
      FormationSlot(x: 0.0766, y: 0.2099, label: 'Sol Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.2327, y: 0.1752, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.7505, y: 0.1824, label: 'Stoper', roleId: 'stoper', group: 'DC'),
      FormationSlot(x: 0.9328, y: 0.2099, label: 'Sağ Bek', roleId: 'bek', group: 'DL/DR'),
      FormationSlot(x: 0.4945, y: 0.1808, label: 'Libero', roleId: 'libero', group: 'DC'),
      FormationSlot(x: 0.3023, y: 0.5014, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.7088, y: 0.5001, label: 'Merkez Orta Saha', roleId: 'merkez_orta_saha', group: 'MC'),
      FormationSlot(x: 0.3023, y: 0.8447, label: 'Sol Kanat', roleId: 'firsatci_forvet', group: 'ST'),
      FormationSlot(x: 0.4870, y: 0.4147, label: 'Regista', roleId: 'regista', group: 'DM'),
      FormationSlot(x: 0.7088, y: 0.8447, label: 'Sağ Kanat', roleId: 'forvet', group: 'ST'),
    ],
  ),
];

/// id -> Formation, hizli arama icin.
final Map<String, Formation> kFormationsById = {for (final f in kFormations) f.id: f};
