// GENERATED by scenario_creator. Do not edit by hand.
// Kaynak: scenario_creator/tackle/*.json  (schema 1)
// Uretim: 2026-09-17T19:17:58+03:00
//
// `tackle_scenarios.dart` bunlari kendi tiplerine cevirir; havuzlara
// aile adiyla girdikleri icin yeni bir kayit hicbir listeye elle
// eklenmek zorunda degil (match_scenarios.dart:131-144).

typedef TackleSpec = ({
  String id,
  String kind,
  String title,
  String brief,
  double closeScale,
  double windowScale,
});

const kTackleSpecs = <TackleSpec>[
  (
    id: 'press_centre_back_dwell',
    kind: 'press',
    title: 'Stoper topu fazla tuttu',
    brief: 'Rakip stoper topu ayağında uyuttu. Ağır adam, önü açık — yetişmek kolay, mesele ne zaman dalacağın.',
    closeScale: 1.2500,
    windowScale: 1.1000,
  ),
  (
    id: 'press_back_pass',
    kind: 'press',
    title: 'Kaleciye dönen top',
    brief: 'Top geriye, kaleciye gidiyor. Uzun bir koşu; tempoyu bozmazsan ceza sahasına girmeden yetişirsin.',
    closeScale: 0.8000,
    windowScale: 1.1500,
  ),
  (
    id: 'press_touchline_trap',
    kind: 'press',
    title: 'Bek çizgiye sıkıştı',
    brief: 'Bek taç çizgisine yaslandı, çıkacak yeri yok. Dar alanda topu gövdesiyle saklıyor, aralık küçük.',
    closeScale: 1.1000,
    windowScale: 0.8500,
  ),
  (
    id: 'contain_pivot_turn',
    kind: 'contain',
    title: 'Pivot dönmek üzere',
    brief: 'Ön libero topu aldı, omzunun üstünden baktı. Dönerse hat kırılır — teknik adam, top ayağından hiç ayrılmıyor.',
    closeScale: 1.0000,
    windowScale: 0.8000,
  ),
  (
    id: 'contain_carry_centre',
    kind: 'contain',
    title: 'Ortadan taşıyor',
    brief: 'Topu alıp merkezden ilerliyor, kimse yardıma gelmiyor. Ne çok hızlı ne çok yavaş: düz bir ikili mücadele.',
    closeScale: 1.0000,
    windowScale: 1.0000,
  ),
  (
    id: 'contain_switch_to_wing',
    kind: 'contain',
    title: 'Top kanada açıldı',
    brief: 'Oyun tek pasla karşı kanada geçti. Uzun bir yatay koşu; adam topu kontrol etmeden üstüne varman gerek.',
    closeScale: 0.7500,
    windowScale: 1.1000,
  ),
  (
    id: 'recovery_last_man',
    kind: 'recovery',
    title: 'Son adam sensin',
    brief: 'Arkanda kaleciden başka kimse yok. Temiz topa gitmek zorundasın — aralık dar ve hatanın affı yok.',
    closeScale: 0.9000,
    windowScale: 0.8000,
  ),
  (
    id: 'recovery_shoulder_duel',
    kind: 'recovery',
    title: 'Omuz omuza',
    brief: 'Forvetle yan yana koşuyorsunuz. Güçlü ama ağır bir adam; yetişirsin, devirmeden ayırman lazım.',
    closeScale: 1.2000,
    windowScale: 0.9000,
  ),
  (
    id: 'recovery_cover_the_cross',
    kind: 'recovery',
    title: 'Ortayı kapatmaya',
    brief: 'Kanat dışarıdan açtı, ortayı yapmadan kapatman gerek. Hızlı adam, mesafe uzun — koşuyu erken başlat.',
    closeScale: 0.7800,
    windowScale: 1.0500,
  ),
];
